packages/socat: disable package due to compilation error
Error was:

 In file included from /data/data/com.termux.musl/files/usr/include/linux/if_tun.h:20,
                  from sysincludes.h:146,
                  from xiosysincludes.h:11,
                  from xioparam.c:7:
 /data/data/com.termux.musl/files/usr/include/linux/if_ether.h:139:8: error: redefinition of 'struct ethhdr'